# Generated by Django 6.0.2 on 2026-05-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='skins.skin')),
            ],
        ),
    ]
