# Generated by Django 6.0.2 on 2026-05-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_skin_current_price_pricehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skin',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='skin',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aktuální cena (€)'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='float_value',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Float'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název skinu'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Nákupní cena (€)'),
        ),
        migrations.AlterField(
            model_name='skin',
            name='rarity',
            field=models.CharField(max_length=50, verbose_name='Rarita'),
        ),
    ]
