# Generated by Django 6.0.2 on 2026-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0003_alter_skin_options_alter_skin_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='market_hash_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
