# Generated by Django 6.0.2 on 2026-05-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0004_skin_market_hash_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skin',
            name='market_hash_name',
        ),
    ]
