# Generated by Django 6.0.2 on 2026-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0005_remove_skin_market_hash_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skin',
            options={},
        ),
        migrations.RemoveField(
            model_name='skin',
            name='created_at',
        ),
        migrations.AddField(
            model_name='skin',
            name='is_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='skin',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='skin',
            name='float_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='skin',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skin',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='skin',
            name='rarity',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
